name: Action test
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor run
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        #args: 
        #format: 'pdf'
      env:
        TEST: |-
          asciidoctor -r asciidoctor-diagram  test/index.adoc
          asciidoctor -r asciidoctor-diagram  test/index.adoc
          asciidoctor -r asciidoctor-diagram  test/subdir/subdir.adoc
          asciidoctor -r asciidoctor-diagram  test/subdir/subsubdir/index.adoc
          asciidoctor -r asciidoctor-diagram  test/subdir/subsubdir/subsubdir.adoc
          asciidoctor -r asciidoctor-diagram  test/subdir/subsubdir/vamoose.adoc
          asciidoctor -r asciidoctor-diagram  test/subdir2/subdir2.adoc
