name: Action test
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor run
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
      env:
        TEST: |-
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subdir.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/subsubdir.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/vamoose.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir2/subdir2.adoc
    - name: Test Asciidoctor run with args
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        asciidoctor-args: '-a revdate=`date +%Y-%m-%d` --failure-level=ERROR'
      env:
        TEST: |-
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subdir.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/index.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/subsubdir.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/vamoose.adoc
          asciidoctor -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir2/subdir2.adoc
    - name: Test Asciidoctor PDF run
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        format: 'pdf'
      env:
        TEST: |-
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subdir.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/subsubdir.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir/subsubdir/vamoose.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json  test/subdir2/subdir2.adoc
    - name: Test Asciidoctor PDF run with args
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        format: pdf
        asciidoctor-args: '-a revdate=`date +%Y-%m-%d` --failure-level=ERROR'
      env:
        TEST: |-
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subdir.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/index.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/subsubdir.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir/subsubdir/vamoose.adoc
          asciidoctor-pdf -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/subdir2/subdir2.adoc
