name: Action test
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor run
      uses: ./
      with:
        files: '*.adoc **/*.adoc'
        #args: 
        #format: 'pdf'
      env:
        TEST: 'sk: test-service-key p: test-project bn: test-bucket-name bp: . bf: . sw: false hpp: index.html epp: 404.html'
